# Generated by Django 2.0.1 on 2018-01-17 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skelbiu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='publish_until',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
