# Generated by Django 2.0.1 on 2018-02-08 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skelbiu', '0002_advertisement_publish_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '61234567'. Do not include +370 or 8.", regex='^\\d{8,8}$')]),
        ),
    ]
