# Generated by Django 2.0.1 on 2018-02-08 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skelbiu', '0003_auto_20180208_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skelbiu.PhoneModel'),
        ),
    ]
