# Generated by Django 2.0.1 on 2018-02-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skelbiu', '0004_auto_20180208_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='publish_until',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='city',
            field=models.CharField(default='Vilnius', max_length=20),
        ),
    ]
