# Generated by Django 2.0.1 on 2018-02-13 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skelbiu', '0005_auto_20180208_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkelbiuAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=256)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skelbiu.PhoneModel')),
            ],
        ),
    ]
