# Generated by Django 2.0.1 on 2018-02-13 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skelbiu', '0006_skelbiuaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='phone',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='skelbiu_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='skelbiu.SkelbiuAccount'),
            preserve_default=False,
        ),
    ]
