# Generated by Django 2.0.1 on 2018-02-13 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skelbiu', '0007_auto_20180213_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='skelbiu_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertisements', to='skelbiu.SkelbiuAccount'),
        ),
    ]
